  /**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
**/

#include <stdint.h>

int main(void)
{

	uint32_t *ptClock   = (uint32_t*)0x40023830;
	uint32_t *ptPinMode = (uint32_t*)0x40020000;
	uint32_t *ptDataOut = (uint32_t*)0x40020014;

	// READING PART PIN PA0
	uint32_t *ptReadPinMode = (uint32_t*)0x40020800;
	uint32_t *ptReadDataIn  = (uint32_t*)0x40020810;

	// 1.Enable the clock peripheral
	*ptClock |= (1<<0); // CLOCK FOR GPIO A
	*ptClock |= (1<<2); // CLOCK FOR GPIO C


	// 2. Turn pin mode on
	//// a. Clear the two bit position
	*ptPinMode &= ~(3<<10); //0xFFFFF3FF ~(11<<10)
	*ptPinMode |= (1<<10); //0x400

	*ptReadPinMode &= ~(3<<0); // Clear fist two bits ~(11<<1)
//	*ptPinMode |= (1<<0); // Toggle last LED


	while(1)
	{
		uint8_t pinStatus = (uint8_t)(	*ptReadDataIn & 0x1);

		if(pinStatus)
		{
			*ptDataOut |= (1<<5);//0x20
		}
		else
		{
			*ptDataOut &= ~(1<<5);//0x20

		}
	}

}
